// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlite

import (
	"context"
)

type Querier interface {
	//CreateUser
	//
	//  INSERT INTO users (id, email, name, created_at, updated_at)
	//  VALUES (?, ?, ?, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
	//  RETURNING id, email, name, created_at, updated_at
	CreateUser(ctx context.Context, arg *CreateUserParams) (*Users, error)
	//DeleteUser
	//
	//  DELETE FROM users WHERE id = ?
	DeleteUser(ctx context.Context, id string) error
	//GetUser
	//
	//  SELECT id, email, name, created_at, updated_at FROM users WHERE id = ? LIMIT 1
	GetUser(ctx context.Context, id string) (*Users, error)
	//GetUserByEmail
	//
	//  SELECT id, email, name, created_at, updated_at FROM users WHERE email = ? LIMIT 1
	GetUserByEmail(ctx context.Context, email string) (*Users, error)
	//ListUsers
	//
	//  SELECT id, email, name, created_at, updated_at FROM users ORDER BY created_at DESC LIMIT ? OFFSET ?
	ListUsers(ctx context.Context, arg *ListUsersParams) ([]*Users, error)
	//UpdateUser
	//
	//  UPDATE users
	//  SET email = ?, name = ?, updated_at = CURRENT_TIMESTAMP
	//  WHERE id = ?
	//  RETURNING id, email, name, created_at, updated_at
	UpdateUser(ctx context.Context, arg *UpdateUserParams) (*Users, error)
}

var _ Querier = (*Queries)(nil)
