# Custom golangci-lint plugin configuration for template-arch-lint
# This configuration integrates the unified template-arch-lint plugin
# providing filename validation, CMD single main enforcement, 
# import cycle detection, and code duplication analysis.

version: "2"

linters:
  settings:
    custom:
      # Template Arch Lint Plugin
      template-arch-lint:
        path: ./plugins/template-arch-lint/template-arch-lint.so
        description: "Unified enterprise Go architecture and code quality enforcement plugin"
        original-url: github.com/LarsArtmann/template-arch-lint
        settings:
          # Plugin-specific settings (passed to the New() function)
          filename-validator:
            enable: true
            strict-naming: true
            check-package-alignment: true
            
          cmd-single-main:
            enable: true
            enforce-main-function: true
            validate-package-name: true
            
          import-cycle-detector:
            enable: true
            check-indirect-cycles: true
            max-cycle-length: 10
            
          code-duplication-detector:
            enable: true
            min-tokens: 15
            similarity-threshold: 0.8
            max-duplicates-per-file: 5

  enable:
    # Enable our custom plugin (custom linters are enabled by default but being explicit)
    - template-arch-lint
  
  disable:
    # Disable built-in linters that might conflict
    - dupl  # We have our own code duplication detector

# Integration with existing .golangci.yml
# Users should include this file or merge settings into their main config
issues:
  exclude-rules:
    # Allow some flexibility for generated files
    - path: ".*_gen\\.go$|.*\\.pb\\.go$|.*_templ\\.go$"
      linters:
        - filename-validator
        - code-duplication-detector