# Custom golangci-lint plugin configuration for template-arch-lint
# This configuration integrates the unified template-arch-lint plugin
# providing filename validation, CMD single main enforcement, 
# import cycle detection, and code duplication analysis.

version: 2

# Plugin configuration
plugins:
  - module: 'template-arch-lint'
    import: 'github.com/LarsArtmann/template-arch-lint/plugins/template-arch-lint'
    version: v1.0.0
    settings:
      path: ./plugins/template-arch-lint/template-arch-lint.so
      description: "Unified enterprise Go architecture and code quality enforcement plugin"
      
      # Plugin-specific settings (these would be passed to the New() function)
      filename-validator:
        enable: true
        strict-naming: true
        check-package-alignment: true
        
      cmd-single-main:
        enable: true
        enforce-main-function: true
        validate-package-name: true
        
      import-cycle-detector:
        enable: true
        check-indirect-cycles: true
        max-cycle-length: 10
        
      code-duplication-detector:
        enable: true
        min-tokens: 15
        similarity-threshold: 0.8
        max-duplicates-per-file: 5

# Linter settings to enable the custom analyzers
linters:
  enable:
    # Enable our custom analyzers
    - filename-validator
    - cmd-single-main  
    - import-cycle-detector
    - code-duplication-detector
  
  disable:
    # Disable built-in linters that might conflict
    - dupl  # We have our own code duplication detector

# Integration with existing .golangci.yml
# Users should include this file or merge settings into their main config
issues:
  exclude-rules:
    # Allow some flexibility for generated files
    - path: ".*_gen\\.go$|.*\\.pb\\.go$|.*_templ\\.go$"
      linters:
        - filename-validator
        - code-duplication-detector