version: "2"
run:
  timeout: 5m
  go: "1.25"
  build-tags: []
  modules-download-mode: readonly
  allow-parallel-runners: true
  allow-serial-runners: false
  issues-exit-code: 1
  tests: true
output:
  formats: {}
linters:
  enable:
    - mirror
    - forcetypeassert
    - iface
    - testifylint
    - exptostd
    - unqueryvet
    - revive
    - errorlint
    - fatcontext
    - gochecknoinits
    - nolintlint
    - exhaustruct
    - gocyclo
    - canonicalheader
    - protogetter
    - ireturn
    - errchkjson
    - perfsprint
    - goprintffuncname
    - nlreturn
    - inamedparam
    - promlinter
    - containedctx
    - reassign
    - cyclop
    - thelper
    - spancheck
    - bidichk
    - predeclared
    - govet
    - testableexamples
    - unparam
    - noctx
    - embeddedstructfieldcheck
    - nosprintfhostport
    - gomoddirectives
    - intrange
    - dupl
    - importas
    - forbidigo
    - zerologlint
    - ginkgolinter
    - mnd
    - durationcheck
    - loggercheck
    - wrapcheck
    - iotamixing
    - gocheckcompilerdirectives
    - sqlclosecheck
    - goconst
    - unused
    - gochecksumtype
    - gocognit
    - godoclint
    - usetesting
    - wastedassign
    - nakedret
    - nilerr
    - sloglint
    - ineffassign
    - gosec
    - maintidx
    - musttag
    - copyloopvar
    - dupword
    - tparallel
    - unconvert
    - exhaustive
    - gomodguard
    - tagalign
    - testpackage
    - whitespace
    - modernize
    - recvcheck
    - varnamelen
    - misspell
    - makezero
    - staticcheck
    - bodyclose
    - prealloc
    - funcorder
    - godox
    - interfacebloat
    - rowserrcheck
    - lll
    - gocritic
    - nestif
    - contextcheck
    - tagliatelle
    - godot
    - nilnesserr
    - nilnil
    - errcheck
    - gochecknoglobals
    - nonamedreturns
    - funlen
    - grouper
    - usestdlibvars
    - decorder
    - asasalint
formatters:
  enable:
    - gofumpt
    - goimports
issues: {}
