version: "2"
run:
  timeout: 5m
  go: "1.25"
  build-tags: []
  modules-download-mode: readonly
  allow-parallel-runners: true
  allow-serial-runners: false
  issues-exit-code: 1
  tests: true
output:
  formats: {}
linters:
  enable:
    - nilerr
    - embeddedstructfieldcheck
    - containedctx
    - godoclint
    - gochecknoinits
    - gocognit
    - modernize
    - asciicheck
    - recvcheck
    - staticcheck
    - mirror
    - cyclop
    - predeclared
    - thelper
    - noctx
    - unconvert
    - sloglint
    - nolintlint
    - nestif
    - copyloopvar
    - makezero
    - protogetter
    - zerologlint
    - wsl_v5
    - goprintffuncname
    - gocritic
    - asasalint
    - exhaustive
    - forcetypeassert
    - errname
    - importas
    - forbidigo
    - whitespace
    - reassign
    - testifylint
    - promlinter
    - ginkgolinter
    - usetesting
    - goconst
    - contextcheck
    - spancheck
    - gocyclo
    - mnd
    - nonamedreturns
    - testableexamples
    - fatcontext
    - godot
    - funcorder
    - ineffassign
    - nlreturn
    - dupl
    - unqueryvet
    - musttag
    - maintidx
    - iotamixing
    - funlen
    - gochecknoglobals
    - varnamelen
    - prealloc
    - inamedparam
    - unused
    - gocheckcompilerdirectives
    - exhaustruct
    - govet
    - tparallel
    - godox
    - bodyclose
    - wrapcheck
    - gosec
    - unparam
    - gomoddirectives
    - dupword
    - revive
    - bidichk
    - noinlineerr
    - arangolint
    - canonicalheader
    - paralleltest
    - loggercheck
    - exptostd
    - errchkjson
    - misspell
    - grouper
    - goheader
    - perfsprint
    - ireturn
    - decorder
    - tagalign
    - gosmopolitan
    - depguard
    - interfacebloat
    - durationcheck
    - usestdlibvars
    - nakedret
    - intrange
    - gochecksumtype
    - errcheck
    - nilnesserr
    - gomodguard
    - wastedassign
    - testpackage
    - sqlclosecheck
    - iface
    - nilnil
    - nosprintfhostport
    - err113
    - dogsled
    - tagliatelle
    - rowserrcheck
    - errorlint
formatters:
  enable:
    - gofumpt
    - goimports
    - golines
issues: {}
