version: "2"
run:
  timeout: 5m
  go: "1.25"
  build-tags: []
  modules-download-mode: readonly
  allow-parallel-runners: true
  allow-serial-runners: false
  issues-exit-code: 1
  tests: true
output:
  formats: {}
linters:
  enable:
    - usestdlibvars
    - exhaustruct
    - rowserrcheck
    - usetesting
    - depguard
    - govet
    - unparam
    - maintidx
    - zerologlint
    - goconst
    - testpackage
    - tparallel
    - importas
    - gomoddirectives
    - recvcheck
    - misspell
    - interfacebloat
    - sqlclosecheck
    - modernize
    - asciicheck
    - iotamixing
    - noctx
    - grouper
    - funlen
    - iface
    - nakedret
    - nlreturn
    - canonicalheader
    - goheader
    - wsl_v5
    - goprintffuncname
    - dupl
    - errorlint
    - gocritic
    - forbidigo
    - godox
    - nilerr
    - durationcheck
    - unconvert
    - nilnil
    - asasalint
    - nosprintfhostport
    - testableexamples
    - intrange
    - paralleltest
    - perfsprint
    - lll
    - sloglint
    - ireturn
    - staticcheck
    - err113
    - embeddedstructfieldcheck
    - gochecknoglobals
    - fatcontext
    - nolintlint
    - gocheckcompilerdirectives
    - nestif
    - bodyclose
    - mirror
    - whitespace
    - contextcheck
    - copyloopvar
    - godot
    - spancheck
    - dogsled
    - containedctx
    - cyclop
    - godoclint
    - dupword
    - loggercheck
    - exhaustive
    - unqueryvet
    - varnamelen
    - wrapcheck
    - tagliatelle
    - reassign
    - exptostd
    - predeclared
    - decorder
    - gochecknoinits
    - gocyclo
    - tagalign
    - revive
    - gocognit
    - prealloc
    - bidichk
    - mnd
    - makezero
    - protogetter
    - nonamedreturns
    - inamedparam
    - gosec
    - gochecksumtype
    - errcheck
    - gosmopolitan
    - musttag
    - nilnesserr
    - noinlineerr
    - funcorder
    - arangolint
    - thelper
    - testifylint
    - ineffassign
    - gomodguard
    - forcetypeassert
    - errname
    - promlinter
    - wastedassign
    - ginkgolinter
    - unused
    - errchkjson
formatters:
  enable:
    - gofumpt
    - goimports
    - golines
issues: {}
