# Production configuration example
# This demonstrates production-ready settings

server:
  host: "0.0.0.0"
  port: 8080
  read_timeout: "10s"
  write_timeout: "30s"
  idle_timeout: "120s"
  graceful_shutdown_timeout: "30s"

database:
  driver: "postgres"
  dsn: "postgres://user:password@localhost:5432/template_arch_lint?sslmode=require"
  max_open_conns: 100
  max_idle_conns: 10
  conn_max_lifetime: "10m"
  conn_max_idle_time: "5m"

logging:
  level: "warn"
  format: "json"
  output: "/var/log/template-arch-lint/app.log"

app:
  name: "template-arch-lint"
  version: "1.0.0"
  environment: "production"
  debug: false