# Example configuration file for template-arch-lint
# This file demonstrates the configuration structure and default values

server:
  host: "localhost"
  port: 8080
  read_timeout: "5s"
  write_timeout: "10s"
  idle_timeout: "60s"
  graceful_shutdown_timeout: "30s"

database:
  driver: "sqlite3"
  dsn: "./app.db"
  max_open_conns: 25
  max_idle_conns: 5
  conn_max_lifetime: "5m"
  conn_max_idle_time: "5m"

logging:
  level: "info"
  format: "json"
  output: "stdout"

app:
  name: "template-arch-lint"
  version: "1.0.0"
  environment: "development"
  debug: false

observability:
  enabled: true
  service_name: "template-arch-lint"
  service_version: "1.0.0"
  environment: "development"
  sampling_rate: 1.0

  tracing:
    enabled: true
    endpoint: "http://localhost:4318/v1/traces"
    http_details: true
    db_queries: true

  metrics:
    enabled: true
    endpoint: "http://localhost:4318/v1/metrics"
    push_interval: "15s"
    business_metrics: true

  exporters:
    prometheus:
      enabled: true
      port: 2112
      path: "/metrics"

    otlp:
      enabled: true
      endpoint: "http://localhost:4318"
      insecure: true

    jaeger:
      enabled: false
      endpoint: "http://localhost:14268/api/traces"
