# Docker Compose override for local development
# This file extends docker-compose.yml with development-specific settings

version: '3.8'

services:
  app:
    build:
      target: builder  # Use builder stage for development tools
    volumes:
      # Mount source code for hot reload (if using air)
      - .:/app:ro
      - ./config.yaml:/config.yaml:ro
      - ./app.db:/app.db
    environment:
      - APP_LOGGING_LEVEL=debug
      - APP_APP_DEBUG=true
    command: ["/server"]  # Override to use development command if needed

  # Add development database UI (optional)
  db-ui:
    image: coleifer/sqlite-web:latest
    ports:
      - "8081:8080"
    volumes:
      - ./app.db:/data/app.db
    networks:
      - app-network
    depends_on:
      - app