apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: template-arch-lint-dev
  annotations:
    description: "Development environment configuration for template-arch-lint"

# Base configuration
resources:
- ../../base

# Namespace for all resources
namespace: template-arch-lint-dev

# Name prefix for all resources
namePrefix: dev-

# Common labels for all resources
labels:
- pairs:
    environment: development
    tier: dev
    version: latest

# Common annotations
commonAnnotations:
  environment: development
  managed-by: kustomize

# Image transformations
images:
- name: template-arch-lint
  newTag: latest
  
# Patches for development environment
patches:
# Reduce resource requirements for dev
- patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/resources/limits/cpu
      value: 200m
    - op: replace
      path: /spec/template/spec/containers/0/resources/limits/memory
      value: 128Mi
    - op: replace
      path: /spec/template/spec/containers/0/resources/requests/cpu
      value: 50m
    - op: replace
      path: /spec/template/spec/containers/0/resources/requests/memory
      value: 64Mi
  target:
    kind: Deployment
    name: template-arch-lint

# Reduce replica count for dev
- patch: |-
    - op: replace
      path: /spec/replicas
      value: 1
  target:
    kind: Deployment
    name: template-arch-lint

# Update HPA for dev environment
- patch: |-
    - op: replace
      path: /spec/minReplicas
      value: 1
    - op: replace
      path: /spec/maxReplicas
      value: 3
  target:
    kind: HorizontalPodAutoscaler
    name: template-arch-lint

# Development-specific ConfigMap patches
- patch: |-
    - op: replace
      path: /data/APP_APP_ENVIRONMENT
      value: development
    - op: replace
      path: /data/APP_LOGGING_LEVEL
      value: debug
    - op: replace
      path: /data/APP_APP_DEBUG
      value: "true"
    - op: replace
      path: /data/APP_OBSERVABILITY_SAMPLING_RATE
      value: "1.0"
  target:
    kind: ConfigMap
    name: template-arch-lint-config

# Development ingress configuration
- patch: |-
    - op: replace
      path: /spec/rules/0/host
      value: dev.template-arch-lint.example.com
    - op: replace
      path: /spec/rules/1/host
      value: api-dev.template-arch-lint.example.com
    - op: replace
      path: /spec/tls/0/hosts/0
      value: dev.template-arch-lint.example.com
    - op: replace
      path: /spec/tls/0/hosts/1
      value: api-dev.template-arch-lint.example.com
  target:
    kind: Ingress
    name: template-arch-lint

# Use local storage class for dev
- patch: |-
    - op: replace
      path: /spec/storageClassName
      value: template-arch-lint-local
  target:
    kind: PersistentVolumeClaim
    name: template-arch-lint-data