# 🏛️ HEXAGONAL ARCHITECTURE TEMPLATE  
# Template for Hexagonal Architecture (Ports & Adapters) pattern
# Customize paths to match your project structure

version: 3
workdir: .

allow:
  depOnAnyVendor: true

# Hexagonal Architecture Components
components:
  # Core - Business Logic (Center of Hexagon)
  core:
    in: internal/core/**
    
  # Ports - Interfaces (Hexagon Boundaries)
  ports-primary:
    in: internal/ports/primary/**
  ports-secondary:
    in: internal/ports/secondary/**
    
  # Adapters - External Integrations
  adapters-primary:
    in: internal/adapters/primary/**
  adapters-secondary:
    in: internal/adapters/secondary/**
    
  # Configuration & Main
  config:
    in: internal/config/**
  main:
    in: cmd/**

# Hexagonal Architecture Dependencies
deps:
  # Core - Pure business logic, no external dependencies
  core:
    anyVendorDeps: true
    mayDependOn: []
    
  # Ports - Define interfaces, can depend on core
  ports-primary:
    mayDependOn: [core]
    
  ports-secondary:
    mayDependOn: [core]
    
  # Primary Adapters - Drive the application (REST, GraphQL, etc.)
  adapters-primary:
    mayDependOn: [core, ports-primary, ports-secondary]
    
  # Secondary Adapters - Driven by application (Database, Email, etc.)  
  adapters-secondary:
    mayDependOn: [core, ports-secondary]
    
  # Configuration & Main - Can depend on all
  config:
    anyVendorDeps: true
    mayDependOn: []
    
  main:
    anyProjectDeps: true

commonComponents:
  - core

exclude:
  - "**/*_test.go"
  - "**/vendor/**"
  - "**/.git/**"