# 📝 STANDARD QUALITY CONFIGURATION
# Balanced approach - Essential linters for most projects
version: "2"

run:
  timeout: 5m
  tests: true
  go: "1.23"

linters:
  enable:
    # Essential Error Handling
    - errcheck       # Unchecked errors
    - errorlint      # Error wrapping
    
    # Core Quality  
    - govet          # Suspicious constructs
    - staticcheck    # Advanced static analysis
    - ineffassign    # Ineffective assignments
    - unused         # Unused code
    
    # Security Basics
    - gosec          # Security audit
    
    # Code Quality
    - goconst        # Repeated constants
    - misspell       # Spelling errors

formatters:
  enable:
    - gofmt          # Standard formatting
    - goimports      # Import formatting

linters-settings:
  gosec:
    excludes:
      - G404  # Allow weak random for non-crypto usage
      
  errcheck:
    check-type-assertions: true
    check-blank: true
    
  staticcheck:
    checks: ["all"]