# Development environment configuration
# This configuration is optimized for local development with verbose logging and relaxed security

server:
  host: "localhost"
  port: 8080
  read_timeout: "5s"
  write_timeout: "10s"
  idle_timeout: "60s"
  graceful_shutdown_timeout: "30s"

database:
  driver: "sqlite3"
  dsn: "./dev.db"
  max_open_conns: 10
  max_idle_conns: 2
  conn_max_lifetime: "5m"
  conn_max_idle_time: "5m"

logging:
  level: "debug"
  format: "text"
  output: "stdout"

app:
  name: "template-arch-lint"
  version: "1.0.0"
  environment: "development"
  debug: true

# Feature flags for development
features:
  enable_debug_endpoints: true
  enable_profiling: true
  enable_hot_reload: true
  enable_cors: true
  enable_request_logging: true
  enable_query_logging: true
  enable_metrics_debug: true

# Security settings (relaxed for development)
security:
  enable_auth: false
  enable_rate_limiting: false
  cors:
    allowed_origins: ["*"]
    allowed_methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
    allowed_headers: ["*"]
    allow_credentials: true
  rate_limit:
    requests_per_minute: 1000
    burst: 100

observability:
  enabled: true
  service_name: "template-arch-lint"
  service_version: "1.0.0"
  environment: "development"
  sampling_rate: 1.0
  
  tracing:
    enabled: true
    endpoint: "http://localhost:4318/v1/traces"
    http_details: true
    db_queries: true
  
  metrics:
    enabled: true
    endpoint: "http://localhost:4318/v1/metrics"
    push_interval: "15s"
    business_metrics: true
  
  exporters:
    prometheus:
      enabled: true
      port: 2112
      path: "/metrics"
    
    otlp:
      enabled: true
      endpoint: "http://localhost:4318"
      insecure: true
    
    jaeger:
      enabled: false
      endpoint: "http://localhost:14268/api/traces"

# Health check configuration
health:
  enabled: true
  endpoint: "/health"
  timeout: "5s"
  check_database: true
  check_external_services: false