# Local development configuration
# This is for individual developer customizations and overrides

server:
  host: "127.0.0.1"
  port: 3000  # Different port to avoid conflicts

database:
  driver: "sqlite3"
  dsn: "./local.db"

logging:
  level: "debug"
  format: "text"
  output: "stdout"

app:
  name: "template-arch-lint-local"
  environment: "local"
  debug: true

features:
  enable_debug_endpoints: true
  enable_profiling: true
  enable_hot_reload: true
  enable_cors: true
  enable_request_logging: true
  enable_query_logging: true
  enable_metrics_debug: true

observability:
  enabled: false  # Disabled for minimal local setup