# Staging environment configuration
# This configuration mimics production but with more verbose logging for debugging

server:
  host: "0.0.0.0"
  port: 8080
  read_timeout: "10s"
  write_timeout: "20s"
  idle_timeout: "90s"
  graceful_shutdown_timeout: "30s"

database:
  driver: "postgres"
  dsn: "${DATABASE_URL}"  # Provided via environment variable
  max_open_conns: 50
  max_idle_conns: 5
  conn_max_lifetime: "10m"
  conn_max_idle_time: "5m"

logging:
  level: "info"
  format: "json"
  output: "stdout"

app:
  name: "template-arch-lint"
  version: "${APP_VERSION}"  # Provided via environment variable
  environment: "staging"
  debug: false

# Feature flags for staging (some experimental features enabled)
features:
  enable_debug_endpoints: false
  enable_profiling: true
  enable_hot_reload: false
  enable_cors: true
  enable_request_logging: true
  enable_query_logging: false
  enable_metrics_debug: true
  enable_beta_features: true
  enable_load_testing: true

# Security settings (production-like but with some debug capabilities)
security:
  enable_auth: true
  enable_rate_limiting: true
  cors:
    allowed_origins: ["https://staging.example.com", "https://staging-api.example.com"]
    allowed_methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
    allowed_headers: ["Content-Type", "Authorization", "X-Requested-With"]
    allow_credentials: true
  rate_limit:
    requests_per_minute: 300
    burst: 50
  tls:
    enabled: true
    cert_file: "${TLS_CERT_FILE}"
    key_file: "${TLS_KEY_FILE}"
  api_keys:
    enabled: true
    header_name: "X-API-Key"

observability:
  enabled: true
  service_name: "template-arch-lint"
  service_version: "${APP_VERSION}"
  environment: "staging"
  sampling_rate: 0.8
  
  tracing:
    enabled: true
    endpoint: "${OTEL_EXPORTER_OTLP_TRACES_ENDPOINT}"
    http_details: true
    db_queries: false
  
  metrics:
    enabled: true
    endpoint: "${OTEL_EXPORTER_OTLP_METRICS_ENDPOINT}"
    push_interval: "30s"
    business_metrics: true
  
  exporters:
    prometheus:
      enabled: true
      port: 2112
      path: "/metrics"
    
    otlp:
      enabled: true
      endpoint: "${OTEL_EXPORTER_OTLP_ENDPOINT}"
      insecure: false
      headers:
        Authorization: "Bearer ${OTEL_AUTH_TOKEN}"
    
    jaeger:
      enabled: false

# Health check configuration
health:
  enabled: true
  endpoint: "/health"
  timeout: "10s"
  check_database: true
  check_external_services: true

# Cache configuration
cache:
  enabled: true
  redis_url: "${REDIS_URL}"
  default_ttl: "1h"
  max_memory: "256mb"

# External services
external:
  api_timeout: "30s"
  retry_attempts: 3
  circuit_breaker:
    enabled: true
    threshold: 5
    timeout: "60s"