apiVersion: v1
kind: ConfigMap
metadata:
  name: template-arch-lint-config
  namespace: template-arch-lint
  labels:
    app.kubernetes.io/name: template-arch-lint
    app.kubernetes.io/instance: template-arch-lint
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/component: configuration
    app.kubernetes.io/part-of: template-arch-lint
  annotations:
    description: "Application configuration for template-arch-lint"
data:
  # Server Configuration
  APP_SERVER_HOST: "0.0.0.0"
  APP_SERVER_PORT: "8080"
  APP_SERVER_READ_TIMEOUT: "5s"
  APP_SERVER_WRITE_TIMEOUT: "10s"
  APP_SERVER_IDLE_TIMEOUT: "60s"
  APP_SERVER_GRACEFUL_SHUTDOWN_TIMEOUT: "30s"
  
  # Database Configuration
  APP_DATABASE_DRIVER: "sqlite3"
  APP_DATABASE_DSN: "/data/app.db"
  APP_DATABASE_MAX_OPEN_CONNS: "25"
  APP_DATABASE_MAX_IDLE_CONNS: "5"
  APP_DATABASE_CONN_MAX_LIFETIME: "5m"
  APP_DATABASE_CONN_MAX_IDLE_TIME: "5m"
  
  # Logging Configuration
  APP_LOGGING_LEVEL: "info"
  APP_LOGGING_FORMAT: "json"
  APP_LOGGING_OUTPUT: "stdout"
  
  # Application Configuration
  APP_APP_NAME: "template-arch-lint"
  APP_APP_VERSION: "1.0.0"
  APP_APP_ENVIRONMENT: "production"
  APP_APP_DEBUG: "false"
  
  # Observability Configuration
  APP_OBSERVABILITY_ENABLED: "true"
  APP_OBSERVABILITY_SERVICE_NAME: "template-arch-lint"
  APP_OBSERVABILITY_SERVICE_VERSION: "1.0.0"
  APP_OBSERVABILITY_ENVIRONMENT: "production"
  APP_OBSERVABILITY_SAMPLING_RATE: "0.1"
  
  # Tracing Configuration
  APP_OBSERVABILITY_TRACING_ENABLED: "true"
  APP_OBSERVABILITY_TRACING_ENDPOINT: "http://otel-collector.observability.svc.cluster.local:4318/v1/traces"
  APP_OBSERVABILITY_TRACING_HTTP_DETAILS: "true"
  APP_OBSERVABILITY_TRACING_DB_QUERIES: "true"
  
  # Metrics Configuration
  APP_OBSERVABILITY_METRICS_ENABLED: "true"
  APP_OBSERVABILITY_METRICS_ENDPOINT: "http://otel-collector.observability.svc.cluster.local:4318/v1/metrics"
  APP_OBSERVABILITY_METRICS_PUSH_INTERVAL: "15s"
  APP_OBSERVABILITY_METRICS_BUSINESS_METRICS: "true"
  
  # Prometheus Exporter Configuration
  APP_OBSERVABILITY_EXPORTERS_PROMETHEUS_ENABLED: "true"
  APP_OBSERVABILITY_EXPORTERS_PROMETHEUS_PORT: "2112"
  APP_OBSERVABILITY_EXPORTERS_PROMETHEUS_PATH: "/metrics"
  
  # OTLP Exporter Configuration
  APP_OBSERVABILITY_EXPORTERS_OTLP_ENABLED: "true"
  APP_OBSERVABILITY_EXPORTERS_OTLP_ENDPOINT: "http://otel-collector.observability.svc.cluster.local:4318"
  APP_OBSERVABILITY_EXPORTERS_OTLP_INSECURE: "true"
  
  # Jaeger Exporter Configuration (disabled by default in production)
  APP_OBSERVABILITY_EXPORTERS_JAEGER_ENABLED: "false"
  APP_OBSERVABILITY_EXPORTERS_JAEGER_ENDPOINT: "http://jaeger-collector.observability.svc.cluster.local:14268/api/traces"
  
  # Application Configuration File
  config.yaml: |
    server:
      host: "0.0.0.0"
      port: 8080
      read_timeout: "5s"
      write_timeout: "10s"
      idle_timeout: "60s"
      graceful_shutdown_timeout: "30s"

    database:
      driver: "sqlite3"
      dsn: "/data/app.db"
      max_open_conns: 25
      max_idle_conns: 5
      conn_max_lifetime: "5m"
      conn_max_idle_time: "5m"

    logging:
      level: "info"
      format: "json"
      output: "stdout"

    app:
      name: "template-arch-lint"
      version: "1.0.0"
      environment: "production"
      debug: false

    observability:
      enabled: true
      service_name: "template-arch-lint"
      service_version: "1.0.0"
      environment: "production"
      sampling_rate: 0.1
      
      tracing:
        enabled: true
        endpoint: "http://otel-collector.observability.svc.cluster.local:4318/v1/traces"
        http_details: true
        db_queries: true
      
      metrics:
        enabled: true
        endpoint: "http://otel-collector.observability.svc.cluster.local:4318/v1/metrics"
        push_interval: "15s"
        business_metrics: true
      
      exporters:
        prometheus:
          enabled: true
          port: 2112
          path: "/metrics"
        
        otlp:
          enabled: true
          endpoint: "http://otel-collector.observability.svc.cluster.local:4318"
          insecure: true
        
        jaeger:
          enabled: false
          endpoint: "http://jaeger-collector.observability.svc.cluster.local:14268/api/traces"