//go:build sqlite3

// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"time"

	"github.com/LarsArtmann/template-arch-lint/internal/domain/values"
)

type Users struct {
	ID       values.UserID `db:"id" json:"id"`
	Email    string        `db:"email" json:"email"`
	Name     string        `db:"name" json:"name"`
	Created  time.Time     `db:"created" json:"created"`
	Modified time.Time     `db:"modified" json:"modified"`
}
